---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: okta-provisioning-agent-filesync
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app: okta-provisioning-agent
                  topologyKey: "kubernetes.io/hostname"
          restartPolicy: OnFailure
          containers:
          - name: okta-provisioning-agent-filesync
            image: amazon/aws-cli
            command: ["aws"]
            args: ["s3", "cp", "s3://bucket/file.csv", "/mnt/data", "--debug"]
            volumeMounts:
            - mountPath: "/mnt/data"
              name: data
          serviceAccountName: irsa-okta
          volumes:
          - name: data
            persistentVolumeClaim:
              claimName: okta-provisioning-agent
  schedule: "* * * * *"
